name: Linting & Code Quality
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        conda env update --file conda-environment.yml --name base
        pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Run Pre-Commit
      run: |
        # Disable linting for now
        # poetry run pre-commit run --all-files
